# Generated by Django 4.2.1 on 2023-05-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
