# Generated by Django 4.2.1 on 2023-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accesslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslist',
            name='alias',
            field=models.CharField(default='', max_length=255),
        ),
    ]
